server:
  port: 8001
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect
        default_schema: mess
  datasource:
    url: jdbc:postgresql://localhost:5432/mess
    username: postgres
    password: 4dm1n
    driver-class-name: org.postgresql.Driver
    
